---
title: "Stacked bar plots"
author: "John Sterrett"
date: "2023-01-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(tidyverse,
               data.table,
               ggplot2,
               phyloseq,
               patchwork,
               microshades,
               cowplot,
               qiime2R)
```

# Load data
```{r}
pseq <- qza_to_phyloseq(features="Data/noMito_noChloro-filtered-table.qza",
                        taxonomy="Data/taxonomy-silva.qza",
                        metadata="Data/IBS-metadata.txt")

temp <- sample_data(pseq) %>% as.data.frame()
temp[temp$IBS.Type=="control", "IBS.Type"] <- "Healthy Control"
sample_data(pseq) <- temp

lipids <- fread("Data/lipids_samples.tsv")
rownames(lipids) <- lipids$V1
lipids$V1 <- NULL

metadata <- fread("Data/IBS-metadata.txt") 
metadata[metadata$`IBS Type`=="control", "IBS Type"] <- "Healthy Control"

```

# Taxa barplot
```{r}
# prep the microshades colors
mdf_prep <- prep_mdf(pseq, subgroup_level="Genus")
# sort the phylum names
phylum_table <- tax_glom(pseq, taxrank="Phylum", ) %>% otu_table()
phyla.otunames <- rownames(phylum_table)
taxonomy.table <- pseq %>% tax_table() %>% as.data.frame()

phylums <- taxonomy.table[phyla.otunames,"Phylum"]

sorted_phylums <- phylums[order(rowSums(phylum_table), decreasing=T)]
# create the colors object
color_objs_GP <- create_color_dfs(mdf_prep, selected_groups = sorted_phylums[5:1], 
                                  cvd = TRUE)
# Extract
mdf_GP <- color_objs_GP$mdf
cdf_GP <- color_objs_GP$cdf
# create a custom legend
GP_legend <-custom_legend(mdf_GP, cdf_GP, 
                          legend_key_size=unit(0.4, "cm"),
                          legend_text_size=10)

# plot
plot <- plot_microshades(mdf_GP, cdf_GP)
plot_1 <- plot + scale_y_continuous(labels = scales::percent, expand = expansion(0)) +
    theme_bw() + 
    theme(legend.position = "none")  +
    theme(axis.text.x = element_blank()) +
    facet_grid(~(factor(IBS.Type,levels=c("Healthy Control", "IBS-D", "IBS-M", "IBS-C"))),
                     scales="free_x", space="free_x"
             )

multi <- plot_grid(plot_1, GP_legend,  rel_widths = c(1, .25))
multi

ggsave("Figures/taxa-bar-phyum-genus-microshades.pdf",plot=multi,height=8,width=10)


```

# Lipids
## Setup
```{r}
lipids <- lipids %>% 
    filter(!rownames(lipids) %in% c("pval", "-log10 pval", 
                                    "fold change", "log2 fold change")) %>%
    select(-c("IBS", "IBS Type"))

hier.mat <- matrix(nrow=ncol(lipids), ncol=4)

lipid.names <- colnames(lipids)
lipid.forms <- lipid.names %>%
    sapply(FUN=function(x) str_split(x, "\\(")[[1]][2])
lipid.forms <- substr(lipid.forms, 1, nchar(lipid.forms)-1)

unsaturated <- grepl(x=lipid.forms, pattern="n")
hier.mat[unsaturated,1] <- "Unsaturated"
hier.mat[!unsaturated,1] <- "Saturated"

omega <- lipid.forms %>% 
    sapply(FUN=function(x) paste("Omega", 
                                 str_split(x, "n")[[1]][2]))

omega[omega=="Omega NA"] <- "Saturated"
hier.mat[,2] <- omega

lip.leng <- substr(lipid.forms, 1, 2)
hier.mat[,3] <- lip.leng

rownames(hier.mat) <- names(lipid.forms)
hier.mat[,4] <- lipid.forms



mbl.pseq <- phyloseq(otu_table(t(lipids), taxa_are_rows=T),
                     tax_table(hier.mat),
                     sample_data=sample_data(metadata))

prep_mdf_norel <- function(ps,
                           subgroup_level = "Genus")
    {

      if (!requireNamespace("phyloseq", quietly = TRUE)) {
        stop("Package \"phyloseq\" needed for this function to work. Please install it.",
             call. = FALSE)
      }

      if (!requireNamespace("speedyseq", quietly = TRUE)) {
        stop("Package \"speedyseq\" needed for this function to work. Please install it.",
             call. = FALSE)
      }


    # Agglomerate, normalizes, and melts phyloseq object -----

    if (!(subgroup_level %in% colnames(phyloseq::tax_table(ps)))) {
      stop("'subgroup_level' does not exist")
    }

    mdf <- ps %>%
        speedyseq::tax_glom(subgroup_level) %>%
        speedyseq::psmelt()

    # Removes 0 abundance
    mdf_prep <- mdf[mdf$Abundance > 0, ]


    # Return melted and prepped data frame -----
    return(mdf_prep)
}
```

## Make plot {.tabset}
### Sat/unsat-name
```{r}
# prep the microshades colors
mdf_prep <- prep_mdf_norel(mbl.pseq, subgroup_level="ta4")

# create the colors object
color_objs_GP <- create_color_dfs(mdf_prep, group_level="ta1", subgroup_level="ta4",
                                  selected_groups = c("Saturated", "Unsaturated"), 
                                  cvd = TRUE)
# Extract
mdf_GP <- color_objs_GP$mdf
cdf_GP <- color_objs_GP$cdf
# create a custom legend
GP_legend <-custom_legend(mdf_GP, cdf_GP, 
                          group_level="ta1", subgroup_level="ta4",
                          legend_key_size=unit(0.4, "cm"),
                          legend_text_size=10)

# plot
plot <- plot_microshades(mdf_GP, cdf_GP)
plot_1 <- plot + scale_y_continuous(expand = expansion(0)) +
    theme_bw()+ 
  theme(legend.position = "none")  +
  theme(axis.text.x = element_blank()) +
  facet_grid(~IBS.Type, scales="free_x", space="free_x"
             ) + 
    ylab("\u03BCg per g fecal sample dry mass")

multi <- plot_grid(plot_1, GP_legend,  rel_widths = c(1, .25))
multi


```

### Omega-name
```{r}
# prep the microshades colors
mdf_prep <- prep_mdf_norel(mbl.pseq, subgroup_level="ta4")

# create the colors object
color_objs_GP <- create_color_dfs(mdf_prep, group_level="ta2", subgroup_level="ta4",
                                  selected_groups = c("Omega 3", "Omega 6", "Omega 9", "Saturated"), 
                                  cvd = TRUE)
# Extract
mdf_GP <- color_objs_GP$mdf
cdf_GP <- color_objs_GP$cdf
# create a custom legend
GP_legend <-custom_legend(mdf_GP, cdf_GP, 
                          group_level="ta2", subgroup_level="ta4",
                          legend_key_size=unit(0.4, "cm"),
                          legend_text_size=10)

# plot
plot <- plot_microshades(mdf_GP, cdf_GP)
plot_1 <- plot + scale_y_continuous(expand = expansion(0)) +
    theme_bw() +
    theme(legend.position = "none")  +
    theme(axis.text.x = element_blank()) +
    facet_grid(~(factor(IBS.Type,levels=c("Healthy Control", "IBS-D", "IBS-M", "IBS-C"))), 
             scales="free_x", space="free_x"
             ) +
    ylab(latex2exp::TeX("$\\mu$g/g fecal sample dry mass"))

multi <- plot_grid(plot_1, GP_legend,  rel_widths = c(1, .25))
multi

ggsave("Figures/lipid-stacked-bar-omega-name-microshades.pdf",plot=multi,height=8,width=10)
```

### Omega-name faceted
```{r}
# prep the microshades colors
mdf_prep <- prep_mdf_norel(mbl.pseq, subgroup_level="ta4")

# create the colors object
color_objs_GP <- create_color_dfs(mdf_prep, group_level="ta2", subgroup_level="ta4",
                                  selected_groups = c("Omega 5", "Omega 3", "Omega 6", "Omega 9", "Saturated"), 
                                  cvd = TRUE)
# Extract
mdf_GP <- color_objs_GP$mdf
cdf_GP <- color_objs_GP$cdf
# create a custom legend
GP_legend <-custom_legend(mdf_GP, cdf_GP, 
                          group_level="ta2", subgroup_level="ta4",
                          legend_key_size=unit(0.4, "cm"),
                          legend_text_size=10)

# plot
plot <- plot_microshades(mdf_GP, cdf_GP)
plot_1 <- plot + scale_y_continuous(expand = expansion(0)) +
    theme_bw() +
    theme(legend.position = "none")  +
    theme(axis.text.x = element_blank()) +
    facet_grid(factor(ta2, levels=c("Saturated", "Omega 9", "Omega 6", "Omega 3", "Omega 5", "Omega 7"))~(factor(IBS.Type,
                           levels=c("Healthy Control", "IBS-D", "IBS-M", "IBS-C"))), 
             scales="free", space="free_x"
             ) +
    ylab(latex2exp::TeX("$\\mu$g/g fecal sample dry mass"))

multi <- plot_grid(plot_1, GP_legend,  rel_widths = c(1, .25))
multi

ggsave("Figures/lipid-faceted-bar-omega-name-microshades.pdf",plot=multi,height=8,width=10)
```